import { StyleSheet} from 'react-native';

export const RStyle = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#0d0d0f',
      alignItems: 'center',
      justifyContent: 'center',
    },
    car:{
        position: 'relative',
        width: 430,
        height: 200,
        bottom: 100,
        objectFit: 'contain',
        opacity: 0.8,
    },
    input:{
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        height: 190,
        width: 350,
        bottom: 50,
    },
    username:{
        fontSize: 20,
        fontFamily: 'coda-regular',
        borderBottomWidth: 1,
        borderColor: 'snow',
        width: 300,
        height: 40,
        color: 'snow',
        paddingLeft: 20,
        position: 'relative',
        bottom: 20,
    },
    password:{
        fontSize: 20,
        fontFamily: 'coda-regular',
        borderBottomWidth: 1,
        borderColor: 'snow',
        width: 300,
        height: 40,
        color: 'snow',
        paddingLeft: 20,
        position: 'relative',
        top: 20,
    },
    btnContainer:{
        position:'relative',
        width: 400,
        top: 150,
        justifyContent: 'space-between',
        display: 'flex',
        flexDirection: 'column',
        alignSelf: 'center',
        alignItems: 'center',
    }
    ,
    rigstBtn:{
        position: 'relative',
        width: 300,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        borderRadius: 30,
        backgroundColor: 'snow',
        shadowColor: 'snow', 
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 0.8,  
        shadowRadius: 10, 
    },
    registBtnText:{
        position: 'relative',
        fontFamily: 'coda-regular',
        fontSize:20,
    },
  });
